services:
  mysql:
    image: mysql:8.0
    container_name: mysql_teste
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste_vaga
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/00-database.sql:ro

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
