services:
  mysql_teste:
    image: mysql:8.0
    container_name: mysql_teste
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-teste_vaga}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app_password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-root123}"]
      interval: 10s
      timeout: 5s
      retries: 8

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    depends_on:
      mysql_teste:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: mysql_teste
    ports:
      - "${ADMINER_PORT:-8080}:8080"

volumes:
  mysql_data:
